<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email or phone_session_key</name>
   <tag></tag>
   <elementGuidId>e069b3e5-cd64-476e-baf0-09e1346b236d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#session_key</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='session_key']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>deac9f91-61aa-41d8-8b5b-377500bc9bf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-color-text font-sans text-md outline-0 bg-color-transparent grow</value>
      <webElementGuid>9280514d-298a-4186-8b5e-f7fa725dd333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>57d7493a-6f5f-4afe-b656-fb4e5af74a19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>session_key</value>
      <webElementGuid>cb9cd0cc-7fc0-4ef8-8c30-ff87a1e231a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>session_key</value>
      <webElementGuid>365a3c98-4de8-4c12-a95d-d3cff700dfbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>25254b29-b3b1-40bf-a314-1b59aa4da193</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;session_key&quot;)</value>
      <webElementGuid>0ec40d3a-ef16-4a6d-abfa-35e9a40de112</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='session_key']</value>
      <webElementGuid>88c57430-fada-4483-a7d8-8e2f79b60c84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/section/div/div/form/div/div/div/div/input</value>
      <webElementGuid>27e70ce7-d01b-4af3-9d5d-fcfdf2bc6c4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>dad73d34-e117-405b-a84e-e9c4cce94f6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'session_key' and @name = 'session_key' and @type = 'text']</value>
      <webElementGuid>001fcae9-f852-4b15-9f03-520ddcfb54eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
