<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_session_password</name>
   <tag></tag>
   <elementGuidId>256d43a8-402c-4ba3-8fb3-0df633acf14a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#session_password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='session_password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6c3fa1da-10f7-4f63-831d-2ea40d88de13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-color-text font-sans text-md outline-0 bg-color-transparent grow</value>
      <webElementGuid>9a92650d-1dbd-4718-962b-2509176c3c5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>current-password</value>
      <webElementGuid>1f4838fa-5ab4-431e-8176-bedcbcbf79cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>session_password</value>
      <webElementGuid>68a14adc-d069-442a-8101-03fce67fd903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>session_password</value>
      <webElementGuid>0ab9e0a2-26f9-4808-bc6c-96e69ef4e2d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>e4d0d81e-fd5b-439b-9896-1b4d6832ac3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;session_password&quot;)</value>
      <webElementGuid>80dafa88-7d06-4952-a906-f5d05895cadc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='session_password']</value>
      <webElementGuid>479e3707-17db-4ad5-be71-b36c459f83fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/section/div/div/form/div/div[2]/div/div/input</value>
      <webElementGuid>32a1985b-02f3-4cf6-af04-2a7b4960bb3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>24066d1d-7b40-4d2f-b9c5-f1e3f969eef7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'session_password' and @name = 'session_password' and @type = 'password']</value>
      <webElementGuid>b779796d-490c-4d76-867a-fab389b79adc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
