<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ChromeDriverService.Builder</name>
   <tag></tag>
   <elementGuidId>7f3b2381-1834-4281-97b6-d311bef65866</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(6) > a[title=&quot;class in org.openqa.selenium.chrome&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'ChromeDriverService.Builder')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2deacccd-9666-45d9-9054-761e18c3f078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>ChromeDriverService.Builder.html</value>
      <webElementGuid>83a5619c-0f28-4004-9ffa-0063f7db7a89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>class in org.openqa.selenium.chrome</value>
      <webElementGuid>a40c9daa-12c5-41f9-80ac-c5e16c29c93c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>classFrame</value>
      <webElementGuid>0e572384-da98-49a7-b3a6-818f98a820e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ChromeDriverService.Builder</value>
      <webElementGuid>6a7fedad-a687-4bb0-839a-7d1e94e55865</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/div[@class=&quot;indexContainer&quot;]/section[1]/ul[1]/li[6]/a[1]</value>
      <webElementGuid>0f61cf98-acef-47e7-b116-19cd0686bd65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ChromeDriverService/iframe_packageFrame</value>
      <webElementGuid>e2de5fa5-8f63-416d-ab97-938c1c7209fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'ChromeDriverService.Builder')]</value>
      <webElementGuid>ed5c6ff1-59b7-4e0e-82c1-92340b6f69a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ChromeDriverService'])[1]/following::a[1]</value>
      <webElementGuid>313e8275-a01f-4e56-a6d1-caa9542791c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ChromeDriverInfo'])[1]/following::a[2]</value>
      <webElementGuid>01a1c31b-27c9-4ffc-a4d6-2b9881c3ba0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ChromeOptions'])[1]/preceding::a[1]</value>
      <webElementGuid>fdac729f-3ee8-4d64-a083-41f08114cb9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ChromeDriverService.Builder']/parent::*</value>
      <webElementGuid>7d5edee9-d9e4-494d-beb3-36f660663405</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'ChromeDriverService.Builder.html')]</value>
      <webElementGuid>2c2c981e-7e4b-4955-a4d6-a09ab7b1623c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a</value>
      <webElementGuid>7f9b0a48-b96d-498c-8dba-08b6f02843c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'ChromeDriverService.Builder.html' and @title = 'class in org.openqa.selenium.chrome' and (text() = 'ChromeDriverService.Builder' or . = 'ChromeDriverService.Builder')]</value>
      <webElementGuid>7828a26a-a7d2-4ada-8e8d-64d439ed2f09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
