<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sign Out</name>
   <tag></tag>
   <elementGuidId>3c1c284a-eadd-4dbd-b1f2-a19061ee8756</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.global-nav__secondary-link.mv1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ember16']/div/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>affc06ad-f1bb-422c-95d4-abb6e1f9b4e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>global-nav__secondary-link mv1</value>
      <webElementGuid>4613f4d9-554d-4e07-bb5f-c04b9fa876f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/m/logout/?lipi=urn%3Ali%3Apage%3Ad_flagship3_feed%3Bcu01Jf63QCOXgS3N6gfLkw%3D%3D</value>
      <webElementGuid>62f5ac8c-3121-402b-906e-49d51a5ef914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ntt-old-href</name>
      <type>Main</type>
      <value>/m/logout/</value>
      <webElementGuid>07ead20d-a844-42b3-8031-c1d647239995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-artdeco-is-focused</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>611e3f43-991c-4fb0-a64e-081196095d65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        Sign Out
      </value>
      <webElementGuid>4226b188-1e14-4d2c-857e-553f9d995a76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ember16&quot;)/div[@class=&quot;artdeco-dropdown__content-inner&quot;]/ul[@class=&quot;global-nav__secondary-items&quot;]/li[@class=&quot;global-nav__secondary-item global-nav__secondary-item--divider&quot;]/a[@class=&quot;global-nav__secondary-link mv1&quot;]</value>
      <webElementGuid>b1d3d31f-dc6f-4f00-ad41-c70cb938b58d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ember16']/div/ul/li[3]/a</value>
      <webElementGuid>7170a8e5-490f-46b3-9c5b-25d5ed77e9e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sign Out']/parent::*</value>
      <webElementGuid>d250641c-34c6-4372-aaf5-4924df80f24d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/m/logout/?lipi=urn%3Ali%3Apage%3Ad_flagship3_feed%3Bcu01Jf63QCOXgS3N6gfLkw%3D%3D')]</value>
      <webElementGuid>8e3e1070-718d-40fa-89eb-41d95b37603c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[3]/a</value>
      <webElementGuid>8435feaf-499b-4cee-891d-7d855fb18300</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/m/logout/?lipi=urn%3Ali%3Apage%3Ad_flagship3_feed%3Bcu01Jf63QCOXgS3N6gfLkw%3D%3D' and (text() = '
        Sign Out
      ' or . = '
        Sign Out
      ')]</value>
      <webElementGuid>ecc4157c-e360-47cb-97b3-576e6bf9132a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
